Update deploy action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,48 +10,57 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: 检出代码仓库
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       
       - name: 设置 Node.js
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: '16'
+          node-version: '20'
       
-      - name: 安装依赖项
-        run: npm install
-      
-      - name: 构建应用程序
-        run: npm run build
-      
-      - name: 设置 SSH 密钥
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan github.com >> ~/.ssh/known_hosts
+      # TODO: 確認2024是否需要build
+      # - name: build
+        # run: |
+          # cd 2024
+          # npm install
+          # npm run build
 
       - name: Install doctl
         uses: digitalocean/action-doctl@v2
         with:
-            token: ${{ secrets.DIGITALOCEANTOKEN }}
-
+          token: ${{ secrets.DIGITALOCEANTOKEN }}
+      
       - name: 获取 Droplet IP 地址
         id: get-droplet-ip
         run: |
-          DROPLET_IP=$(doctl compute droplet list --format PublicIPv4 --no-header --tag-name my-droplet-tag)
+          DROPLET_IP=$(doctl compute droplet list --format PublicIPv4 --no-header --tag-name website)
+          if [ -z "$DROPLET_IP" ]; then
+            echo "Error: No Droplet IP found. Please check if the Droplet is correctly tagged and has a public IP."
+            exit 1
+          fi
           echo "Droplet IP 地址: $DROPLET_IP"
-          echo "::set-output name=droplet_ip::$DROPLET_IP"
+          echo "droplet_ip=$DROPLET_IP" >> $GITHUB_ENV
       
-      - name: 將應用程序文件複製到 Droplet (develop)
-        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/test-actions'
+      - name: Setup SSH
         run: |
-            scp -o StrictHostKeyChecking=no -r 2024/* ${{ steps.get-droplet-ip.outputs.droplet_ip }}:/var/www/mopcon-dev/2024
-  
-      - name: 將應用程序文件複製到 Droplet (deploy)
-        if: github.ref == 'refs/heads/deploy'
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H ${{ env.droplet_ip }} >> ~/.ssh/known_hosts
+        
+      # TODO: 目前只有html檔,正式開發後可能需要修改來源資料夾
+      - name: 將應用程序文件複製到 Droplet
         run: |
-            scp -o StrictHostKeyChecking=no -r 2024/* ${{ steps.get-droplet-ip.outputs.droplet_ip }}:/var/www/mopcon/2024
+          if [ "${GITHUB_REF}" == "refs/heads/develop" ] || [ "${GITHUB_REF}" == "refs/heads/test-actions" ]; then
+            TARGET_DIR="/var/www/mopcon-dev/2024"
+          elif [ "${GITHUB_REF}" == "refs/heads/deploy" ]; then
+            TARGET_DIR="/var/www/mopcon/2024"
+          else
+            echo "No valid branch for deployment"
+            exit 1
+          fi
+          ssh -o StrictHostKeyChecking=no root@${{ env.droplet_ip }} "mkdir -p ${TARGET_DIR}"
+          scp -o StrictHostKeyChecking=no -r 2024/* root@${{ env.droplet_ip }}:${TARGET_DIR}
         
       - name: 重启 Droplet 上的 Nginx 服务
         run: |
-          ssh -o StrictHostKeyChecking=no ${{ steps.get-droplet-ip.outputs.droplet_ip }} sudo systemctl restart nginx
+          ssh -o StrictHostKeyChecking=no root@${{ env.droplet_ip }} sudo systemctl restart nginx
